### PR TITLE
gh actions native approach:

### PR DESCRIPTION
**Pull request by gajop**
- remove spring-launcher-backend, self-contain the CI to this repo
- build windows builds natively, without wine

### CODE REVIEW

**Comment by gajop** [comment]
Well the build is up at https://github.com/beyond-all-reason/BYAR-Chobby/releases/tag/untagged-563dfeafa7e82e8cd374 but it still crashes for me on Windows. 

Working on a fix.

**Comment by gajop** [comment]
Fixed and released in https://github.com/beyond-all-reason/BYAR-Chobby/releases/tag/untagged-ba8eca73595e5a3fd2a8 ! 

The ENOTDIR thing turned out to be a problem in how I was detecting dev version since electron-is-dev got deprecated.

It does not fix the window resize issue though.

**Comment by gajop** [comment]
https://github.com/beyond-all-reason/BYAR-Chobby/releases/tag/untagged-dd6b59cb0be0bf8ad035 does seems to fix the resize problem; seems it was a spring issue (or rather springsettings.cfg) all along

Please test yourself by installing from the above link, and review - approve if it works for you.

**Comment by Beherith** [comment]
Holy crap resize works dude!

**Pull request merged**
