### PR TITLE
Adjust shown icons in battle room to core_teams decisions

### PR DESCRIPTION
**Pull request by FIr3baL**
allow change values in igl_data.lua for users:
1) showRank true/false
2) showSkill true/false

### CODE REVIEW

**Comment by Beherith** [comment]
Is this wired into the UI?

**Comment by FIr3baL** [comment]
converted to draf,
i´ll include turn off skill :(
showRank = true 
showSkill = true

**Comment by FIr3baL** [comment]
Watch The Fort said:
https://discord.com/channels/549281623154229250/549282587487502347/1066093436719079566
> We should show the minimum possible, we don't want an overwhelming UI
> Rank in player list - yes
> Skill number - no
> Country flag - no
> Sync status - only for those downloading

**Comment by Beherith** [comment]
This is awesome!

**Pull request merged**
