### PR TITLE
Add faction/side selector

### PR DESCRIPTION
**Pull request by rlcevg**
Depends from https://github.com/Spring-Chobby/Chobby/pull/520 because of new gui_side_change_window.lua and api_user_handler.lua changes.

### CODE REVIEW

**Comment by Beherith** [comment]
can merging this before chobby PR #520 gets merged cause any issue?

**Review by gajop — APPROVED** [review]

**Comment by gajop** [comment]
Merging this since the Chobby PR was also merged without any changes

**Comment by gajop** [comment]
@rlcevg @Beherith 
Just an FYI:

I've fixed the typo (https://github.com/Spring-Chobby/Chobby/commit/91a0b4b5e05a03897e69efbdb33e4acab66b273d) & the visual bug where initial the GUI wasn't representative of the underlying model (https://github.com/Spring-Chobby/Chobby/commit/558a0fcf55f058f59da744d2b4c9340f2a5576e7), and I've added default sides for BAR (https://github.com/beyond-all-reason/BYAR-Chobby/commit/5cfc418361226766be3b47f81e4f4181badba564)

Lemme know if I missed anything!

**Comment by Beherith** [comment]
much much <3

**Pull request merged**
