### PR TITLE
Detect corrupt pool and push a popup

### PR DESCRIPTION
**Pull request by AntlerForce**
Addresses #572

### CODE REVIEW

**Comment by WatchTheFort** [comment]
Can this be automated, to fix the issue without any user intervention?

**Comment by Beherith** [comment]
> > Can this be automated, to fix the issue without any user intervention?
> 
> I don't know. There's no Lua wrapper for `FileSystem::Remove()`

os.remove should work, but I would NOT recommend doing it to the entire pool folder one by one.

Beyond-All-Reason.sdd\luaui\Widgets\gui_savegame.lua
  185: 		os.remove(pathNoExtension .. ".lua")
  188: 			os.remove(saveFilePath)

**Comment by 6AKU66** [comment]
When you will release this update please notify engine developers about release of this system to end-users (leave a message in #engine) since it's most likely will skew our desync rate and we need to know causing of that.

**Review by thehobojoe — APPROVED** [review]
PAT

**Pull request merged**
