### PR TITLE
Fine-tuning for scenario023.lua

### PR DESCRIPTION
**Pull request by 6AKU66**
1. Added very MT intensive collision test;
2. Fine-tuned some settings;
3. Some description changes.

### CODE REVIEW

**Comment by WatchTheFort** [comment]
Scenario files are part of the game repo now, the lobby ones don't do anything.

We should really remove them...

**Comment by Ezahiel** [comment]
@WatchTheFort since when? I can't find any update on it and can still see VFS for chobby repo in LuaMenu/widgets/gui_scenario_window.lua
Ln 113: 

local files = VFS.DirList("LuaMenu/configs/gameConfig/byar/scenarios/")

**Comment by WatchTheFort** [comment]
Isn't it this? https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/unit_scenario_script.lua

**Comment by Ezahiel** [comment]
Unfortunately not, but you gave me idea. Will check it over weekend. 
This gadget only allow to use script in scenario

**Pull request merged**
