### PR TITLE
Adapt preloader for BYAR

### PR DESCRIPTION
**Pull request by MooseOnTheLoose**
This image preloader update contains improvements from Zero-K (preloading of checkboxes and other non-image items) and the AddDir entires have been changed to match where BYAR-Chobby has more than 1 image.

These changes aim to reduce the white-flash experience when first loading elements of chobby.

### CODE REVIEW

**Comment by MooseOnTheLoose** [comment]
Here's GoogleFrog's commit for that minimap change: https://github.com/Spring-Chobby/Chobby/commit/0c9814d55f5df8a1dc8961ba4b9fa8892085599a#diff-74369719356ac8c3b9a50f23abd353911faabb5534c71dd877eddab540a3f188

"Speed up chobby loading by not loading wrapper-minimaps." BYAR minimaps are stored differently.

**Comment by Beherith** [comment]
Are you certain that its a good idea to preload this folder?

AddDir("LuaMenu/configs/gameConfig/byar/minimapOverride")

It contains ~200 1K sized images, which could eat a gig of ram easily. Ill time how long it takes to load with this and without.

**Comment by MooseOnTheLoose** [comment]
> Are you certain that its a good idea to preload this folder?
> 
> AddDir("LuaMenu/configs/gameConfig/byar/minimapOverride")
> 
> It contains ~200 1K sized images, which could eat a gig of ram easily. Ill time how long it takes to load with this and without.

No, the only logic I applied was any folder with more than 1 image. I don't know at what point a folder would be too big to wisely preload.

**Comment by Beherith** [comment]
With this commit, hot reload time is 12 seconds, mem usage is 2200 MB

Without the preloader, its 5 seconds reload time, mem usage is also 2200MB.

Hmmmm....

**Comment by Beherith** [comment]
`[t=00:00:02.884927][f=-000001] [VSync::SetInterval] interval=2 (standard)
[t=00:00:02.885566][f=-000001] Minimap parsed:, C:\Users\Peti\AppData\Local\Programs\Beyond-All-Reason\data\maps\Medit_V1.sdd, C:\Users\Peti\AppData\Local\Programs\Beyond-All-Reason\data\LuaMenu\Images\Minimaps\Medit_V1_2.jpg
[t=00:00:03.493378][f=-000001] Minimap parsed:, C:\Users\Peti\AppData\Local\Programs\Beyond-All-Reason\data\maps\Medit_v6.sdd, C:\Users\Peti\AppData\Local\Programs\Beyond-All-Reason\data\LuaMenu\Images\Minimaps\Medit_V6.jpg
[t=00:00:07.820399][f=-000001] [ClientMessage] LOGIN [teh]Beherith PLOZfRh26x0fSgm742UgEA== 0 * LuaLobby Chobby	3270458860 56235860b90f54d9	b sp
`
REmoving that folder:
`[t=00:00:02.973644][f=-000001] [VSync::SetInterval] interval=2 (standard)
[t=00:00:02.974316][f=-000001] Minimap parsed:, C:\Users\Peti\AppData\Local\Programs\Beyond-All-Reason\data\maps\Medit_V1.sdd, C:\Users\Peti\AppData\Local\Programs\Beyond-All-Reason\data\LuaMenu\Images\Minimaps\Medit_V1_2.jpg
[t=00:00:03.602573][f=-000001] Minimap parsed:, C:\Users\Peti\AppData\Local\Programs\Beyond-All-Reason\data\maps\Medit_v6.sdd, C:\Users\Peti\AppData\Local\Programs\Beyond-All-Reason\data\LuaMenu\Images\Minimaps\Medit_V6.jpg
[t=00:00:04.340469][f=-000001] [ClientMessage] LOGIN [teh]Beherith PLOZfRh26x0fSgm742UgEA== 0 * LuaLobby Chobby	3270458860 56235860b90f54d9	b sp
`
I see a bit less flashing with preloader, but not zero flashing

**Comment by MooseOnTheLoose** [comment]
Yes, that's what I have observed too. The language on the Zero-K side of the commits states a "cut-down" on flashing, so this is within expectations.

**Comment by Beherith** [comment]
cool, imo AddDir("LuaMenu/configs/gameConfig/byar/minimapOverride") can be removed, then the game still loads fast and flashes less :)

Thank you for this!

**Comment by MooseOnTheLoose** [comment]
Sounds good.

**Pull request merged**
