### PR TITLE
Maplist searchbox and improved loading from Zero-K

### PR DESCRIPTION
**Pull request by MooseOnTheLoose**
Screenshot_304

BUGS:

-Every term is searchable except Unofficial, even though Certified and Classic work

### CODE REVIEW

**Review by MooseOnTheLoose — COMMENTED** [review]
Self review test

**Comment by MooseOnTheLoose** [comment]
Fixed redraw. Ready to merge unless someone can figure out why Unofficial is not searchable.

**Comment by Beherith** [comment]
Were object.lua and editbox.lua not present in byarchobby or different from in use by vanilla chobby? 

Regarding the unofficial search, i recall using some nasty hacks to add another invisible sorting column to the maps list

**Comment by MooseOnTheLoose** [comment]
> Were object.lua and editbox.lua not present in byarchobby or different from in use by vanilla chobby?

These are present in vanilla chobby but missing functions caused errors.  These versions are from ZK chobby fork.
 
> Regarding the unofficial search, i recall using some nasty hacks to add another invisible sorting column to the maps list

What was the intended goal of these hacks? I deleted the extra column and notice no change.

**Pull request merged**
