### PR TITLE
Implement Flatpak

### PR DESCRIPTION
**Pull request by tobias47n9e**
Still WIP, but ready to be disussed & tested:

This PR adds:

- Flatpak manifest that runs spring-launcher in a container and allows it to download game data
- A `info.beyondallreason.bar.appdata.xml` that would be used to publish the game on flathub.org

**Probably best to squash my commits after all the reviews, because It took a lot of trial and error to get this working**

### CODE REVIEW

**Comment by Beherith** [comment]
Hmm, do you feel this is ready?

**Comment by tobias47n9e** [comment]
@Beherith We could still wait for the review here to finish, so we merge the up to date version: https://github.com/flathub/flathub/pull/2487

**Comment by Beherith** [comment]
Wait a minute, are you kek_ on discord?

**Comment by Beherith** [comment]
To make sure, the flatpak is just the launcher (spring-launcher), which then downloads game, byar-chobby and chobby?

**Comment by p2004a** [comment]
@Beherith Yes, nothing less nothing more.

**Pull request closed without merging**
