### PR TITLE
minor changes to action button

### PR DESCRIPTION
**Pull request by The-Yak**
Screenshot_140

https://cdn.discordapp.com/attachments/549282587487502347/1001590179577995284/Screenshot_140.png

### CODE REVIEW

**Comment by The-Yak** [comment]
Screenshot_143

**Comment by The-Yak** [comment]
Screenshot_144

Changed lighting a bit

**Comment by The-Yak** [comment]
Screenshot_146

**Comment by The-Yak** [comment]
Screenshot_147

**Comment by Beherith** [comment]
Scream if this is ready :)

**Comment by The-Yak** [comment]
This can be merged anytime.

**Pull request merged**
